resources:
  - name: sample_resource_test
    type: GitRepo
    configuration:
      gitProvider: github_jprinet
      path: jprinet/jfrog-pipelines-sample
      branches:
        include: test
  - name: myBuildInfoTest
    type: BuildInfo
    configuration:
      sourceArtifactory:    artifactory_jerome
      buildName:            sample_pipelines_test
      buildNumber:          ${run_number}
      externalCI:           jenkinsIntegration
  - name: myBuildInfoTestPromoted
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_jerome
      buildName: sample_pipelines_test
      buildNumber: '${run_number}'

pipelines:
  - name: sample_pipelines_test

    steps:
      - name: build_native
        type: GradleBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: jprinet/jfrog-pipelines-runner
                tag: latest
          gradleCommand:        clean artifactoryPublish
          sourceLocation:       .
          configFileLocation:   .jfrog/projects
          configFileName:       gradle.yaml
          forceXrayScan:        false
          failOnScan:           false
          autoPublishBuildInfo: true
          inputResources:
            - name: sample_resource_test
          outputResources:
            - name: myBuildInfoTest
          integrations:
            - name: artifactory_jerome
        execution:
          onStart:
            - java -version
            - jfrog -v

      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository:      jerome-mvn-int-local
          includeDependencies:   true
          status:                'DEV OK'
          comment:               'passed DEV pipeline'
          copy:                  false
          inputResources:
            - name:         myBuildInfoTest
              trigger: false
          inputSteps:
            - name: build_native
          outputResources:
            - name:         myBuildInfoTestPromoted
