resources:
  - name: sample_resource_feature
    type: GitRepo
    configuration:
      gitProvider: github_jprinet
      path: jprinet/jfrog-pipelines-sample
      branches:
        include: feature/*

pipelines:
  - name: sample_pipelines_feature

    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: sample_resource_feature
      execution:
        onExecute:
          - echo "Hello World!"

    - name: step_2
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - echo "Goodbye World!"  

    - name: step_3
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - echo "Goodbye Parallel World!"  