resources:
  - name: sample_resource_docker
    type: GitRepo
    configuration:
      gitProvider: github_jprinet
      path: jprinet/jfrog-pipelines-sample
      branches:
        include: feature/add_docker
  - name: myBuildInfoDocker
    type: BuildInfo
    configuration:
      sourceArtifactory:    artifactory_jerome
      buildName:            sample_pipelines_docker
      buildNumber:          ${run_number}

pipelines:
  - name: sample_pipelines_docker
    steps:

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 'artifactory-jerome.soleng-emea-staging.jfrog.team/jerome-docker-dev/hello-pipelines'
          dockerImageTag: ${run_number}
          inputResources:
            - name: sample_resource_docker
          integrations:
            - name: artifactory_jerome

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: jerome-docker-dev
          integrations:
            - name: artifactory_jerome
          inputSteps:
            - name: docker_build

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: myBuildInfoDocker