resources:
  - name: sample_resource_docker
    type: GitRepo
    configuration:
      gitProvider: github_jprinet
      path: jprinet/jfrog-pipelines-sample
      branches:
        include: feature/add_docker
  - name: myBuildInfoDocker
    type: BuildInfo
    configuration:
      sourceArtifactory:    artifactory_jerome
      buildName:            sample_pipelines_docker
      buildNumber:          ${run_number}

pipelines:
  - name: sample_pipelines_docker
    steps:

      - name: configDaemon
        type: Bash
        configuration:
          affinityGroup: dockerGroup
          runtime:
            type: host
        execution:
          onExecute:
            - >
              jq -n  '{ "graph": "/data", "mtu": 1460, "insecure-registries": ["jerome-docker-dev.artifactory-jerome.soleng-emea-staging.jfrog.team"]}' | jq . > /etc/docker/daemon.json
            - sudo systemctl restart docker

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 'jerome-docker-dev.artifactory-jerome.soleng-emea-staging.jfrog.team/hello-pipelines'
          dockerImageTag: ${run_number}
          inputResources:
            - name: sample_resource_docker
          integrations:
            - name: artifactory_jerome
          inputSteps:
            - name: configDaemon

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: jerome-docker-dev
          autoPublishBuildInfo: true
          forceXrayScan: true
          failOnScan: true
          outputResources:
            - name: myBuildInfoDocker
          integrations:
            - name: artifactory_jerome
          inputSteps:
            - name: docker_build
        execution:
          onStart:
            - docker info
