resources:
  - name: sample_resource_bash_test
    type: GitRepo
    configuration:
      gitProvider: github_jprinet
      path: jprinet/jfrog-pipelines-sample
      branches:
        include: feature/add_bash_step

pipelines:
  - name: sample_pipelines_bash_test

    steps:
      - name: build_bash
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: jprinet/jfrog-pipelines-runner
                tag: latest
          environmentVariables:
            JFROG_CLI_OFFER_CONFIG: 'false'
            CI: 'true'
            GRADLE_OPTS: -Dorg.gradle.daemon=false
          inputResources:
            - name: sample_resource_bash_test
        execution:
          onExecute:
            - cd $res_sample_resource_bash_test_resourcePath
            - curl -fL https://getcli.jfrog.io | sh
            - ./jfrog rt c jerome-gcp --interactive=false --url=http://artifactory-jerome.soleng-emea-staging.jfrog.team/artifactory --user=admin --apikey=$API_KEY
            - ./jfrog rt ping
            - ./jfrog rt gradle-config --server-id-resolve=jerome-gcp --server-id-deploy=jerome-gcp --repo-resolve=jerome-mvn-dev --repo-deploy=jerome-mvn-dev --use-wrapper=true
            - ./jfrog rt gradle build artifactoryPublish -Dorg.gradle.daemon=false --build-name=pipelines-gradle-sample-bash --build-number=${run_number}
            - ./jfrog rt bp pipelines-gradle-sample-bash ${run_number}
