resources:
  - name: sample_resource_feature
    type: GitRepo
    configuration:
      gitProvider: github_jprinet
      path: jprinet/jfrog-pipelines-sample
      branches:
        include: feature/add_gradle
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory:    artifactory_jerome
      buildName:            pipelines-gradle-sample
      buildNumber:          ${run_number}
      externalCI:           jenkinsIntegration

pipelines:
  - name: sample_pipelines_feature

    steps:
      - name: build_native
        type: GradleBuild
        configuration:
          gradleCommand:        clean artifactoryPublish
          sourceLocation:       .
          configFileLocation:   .
          configFileName:       gradle-pipelines-config
          forceXrayScan:        false
          failOnScan:           false
          autoPublishBuildInfo: true
          inputResources:
            - name: sample_resource_feature
          outputResources:
            - name: myBuildInfo
          integrations:
            - name: artifactory_jerome
        execution:
          onStart:
            - cd $res_sample_resource_feature_resourcePath
            - ls


