resources:
  - name: sample_resource
    type: GitRepo
    configuration:
      gitProvider: github_jprinet
      path: jprinet/jfrog-pipelines-sample
      branches:
        include: master

pipelines:
  - name: sample_pipelines

    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: sample_resource
      execution:
        onExecute:
          - echo "Hello World!"

    - name: step_2
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - echo "Goodbye World!"  