pipelines:
  - name: jerome_pipelines_docker
    steps:

      - name: configDaemon
        type: Bash
        configuration:
          affinityGroup: dockerGroup
          runtime:
            type: host
        execution:
          onExecute:
            - >
              jq -n  '{ "graph": "/data", "mtu": 1460, "insecure-registries": ["artifactory-us.staging.gcp.devopsacc.team:80/jerome-docker"]}' | jq . > /etc/docker/daemon.json
            - sudo systemctl restart docker

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 'artifactory-us.staging.gcp.devopsacc.team:80/jerome-docker/hello-pipelines'
          dockerImageTag: ${run_number}
          inputResources:
            - name: sample_resource_docker
          integrations:
            - name: Artifactory
          inputSteps:
            - name: configDaemon

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: jerome-docker
          autoPublishBuildInfo: true
          forceXrayScan: true
          failOnScan: true
          outputResources:
            - name: myBuildInfoDocker
          integrations:
            - name: Artifactory
          inputSteps:
            - name: docker_build
        execution:
          onStart:
            - docker info
