pipelines:
  - name: jerome_pipelines_bash_test

    steps:
      - name: build_bash
        type: Bash
        configuration:
          integrations:
            - name: artifactory_secret
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "8.0"
          environmentVariables:
            JFROG_CLI_OFFER_CONFIG: 'false'
            CI: 'true'
            GRADLE_OPTS: -Dorg.gradle.daemon=false
          inputResources:
            - name: sample_resource_bash_test
        execution:
          onExecute:
            - cd $res_sample_resource_bash_test_resourcePath
            - curl -fL https://getcli.jfrog.io | sh
            - ./jfrog rt c arti-gcp --interactive=false --url=http://artifactory-us.staging.gcp.devopsacc.team/artifactory --user=admin --apikey=${int_artifactory_secret_api_key}
            - ./jfrog rt ping
            - ./jfrog rt gradle-config --server-id-resolve=arti-gcp --server-id-deploy=arti-gcp --repo-resolve=jerome-gradle --repo-deploy=jerome-gradle --use-wrapper=true
            - ./jfrog rt gradle build artifactoryPublish -Dorg.gradle.daemon=false --build-name=pipelines-gradle-sample-bash --build-number=${run_number}
            - ./jfrog rt bp pipelines-gradle-sample-bash ${run_number}
